name: macOS CI
# Workflow for building BibleTime for macOS
on:
  push:
    branches:
      - master
  repository_dispatch:
  pull_request: {}

jobs:
  Windows:
    name: build-mac
    runs-on: [macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -e
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install clucene sword
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'


