name: macOS CI
# Workflow for building BibleTime for macOS
on:
  push:
    branches:
      - master
  repository_dispatch:
  pull_request: {}

jobs:
  mac:
    name: build-mac
    runs-on: [macOS-10.15]

    steps:

    - name: "Select Xcode_12.4"
      uses: devbotsxyz/xcode-select@v1
      with:
        version: "12.4"

    - name: Install dependencies
      run: |
        set -e
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install ccache clucene sword create-dmg
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'

    - name: Checkout BibleTime Stable
      run: |
        git clone https://github.com/bibletime/bibletime.git
        cd bibletime
        git checkout stable-3.0
        ls -l
        
    - name: Get BibleTime Docs
      run: |
        git clone https://github.com/bibletime/generated_docs.git

    - name: Configure BibleTime
      shell: bash
      run: |
        mkdir install
        mkdir build
        cd build
        cmake ../bibletime \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX:PATH=../install \
          -DBUILD_HANDBOOK_HTML:BOOL=OFF \
          -DBUILD_HANDBOOK_PDF:BOOL=OFF \
          -DBUILD_HOWTO_HTML:BOOL=OFF \
          -DBUILD_HOWTO_PDF:BOOL=OFF

    - name: Build BibleTime
      shell: bash
      run: |
        cd build
        cmake --build . --config Release

    - name: Install BibleTime
      shell: bash
      run: |
        cd build
        cmake --install . 
        mkdir -p ../install/BibleTime.app/Contents/share/doc/bibletime
        cp -R ../generated_docs/docs/v3.0.2/howto ../install/BibleTime.app/Contents/share/doc/bibletime
        cp -R ../generated_docs/docs/v3.0.2/handbook ../install/BibleTime.app/Contents/share/doc/bibletime

    - name: make dmg
      shell: bash
      run: |
        cd install
        ln -s /Applications .
        create-dmg BibleTime-3.0.2.dmg .

    - name: Save BibleTime Installer
      uses: actions/upload-artifact@v2
      with:
        name: bibletime-macos-installer
        path: install/BibleTime-3.0.2.dmg 
        retention-days: 5

