name: macOS CI
# Workflow for building BibleTime for macOS
on:
  push:
    branches:
      - master
  repository_dispatch:
  pull_request: {}

jobs:
  mac:
    name: build-mac
    runs-on: [macos-latest]

    steps:
    - name: Install dependencies
      run: |
        set -e
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install clucene sword 
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'

    - name: Checkout BibleTime Stable
      uses: actions/checkout@v2
      with:
        repository: bibletime/bibletime
        ref: stable-3.0
        
    - name: Configure
      shell: bash
      run: |
        mkdir build
        mkdir install
        pwd
        ls -l
        cmake \
          -S . \
          -B . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX:PATH=install \
          -DBUILD_HANDBOOK_HTML:BOOL=OFF \
          -DBUILD_HANDBOOK_PDF:BOOL=OFF \
          -DBUILD_HOWTO_HTML:BOOL=OFF \
          -DBUILD_HOWTO_PDF:BOOL=OFF

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config Release

    - name: Install Strip
      shell: bash
      run: cmake --install . --strip

