name: macOS CI
# Workflow for building BibleTime for macOS
on:
  push:
    branches:
      - master
  repository_dispatch:
  pull_request: {}

jobs:
  mac:
    name: build-mac
    runs-on: [macOS-10.15]

    steps:

    - name: "Select Xcode_12.4"
      uses: devbotsxyz/xcode-select@v1
      with:
        version: "12.4"

    - name: Get BibleTime Docs
      run: git clone https://github.com/bibletime/generated_docs.git

    - name: Install dependencies
      run: |
        set -e
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install ccache clucene sword 
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'

    - name: Checkout BibleTime Stable
      uses: actions/checkout@v2
      with:
        repository: bibletime/bibletime
        ref: stable-3.0
        
    - name: Configure BibleTime
      shell: bash
      run: |
        mkdir build
        mkdir install
        echo cbcbcbcb
        pwd
        ls -l
        echo cbcbcbcb
        cmake \
          -S . \
          -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX:PATH=../install \
          -DBUILD_HANDBOOK_HTML:BOOL=OFF \
          -DBUILD_HANDBOOK_PDF:BOOL=OFF \
          -DBUILD_HOWTO_HTML:BOOL=OFF \
          -DBUILD_HOWTO_PDF:BOOL=OFF

    - name: Build BibleTime
      shell: bash
      run: |
        cd build
        echo bbbbbbbb
        pwd
        ls -l
        echo bbbbbbbb
        cmake --build . --config Release

    - name: Install BibleTime
      shell: bash
      run: |
        cd build
        echo ibibibib1
        pwd
        ls -l
        echo ibibibib2
        cmake --install . 
        ls -l ../generated_docs
        ls -l ../generated_docs/docs
        ls -l ../generated_docs/docs/v3.0.2/
        cp -r ../generated_docs/docs/v3.0.2/h* ../install/BibleTime.app/Contents/share/doc/bibletime
        echo ibibibib3

    - name: list files
      shell: bash
      run: |
        cd install
        find . -type f



