# Workflow for building BibleTime for macOS
# build directories
#  <build_home>               The bibletime/bibletime-mac repository
#  <build_home/bibletime      The bibletime/bibletime repository
#  <build_home/generated_docs The bibletime/generated_docs repository
#  <build_home>/build         The directory for building BibleTime
#  <build_home>/install       The install directory for building BibleTime

name: macOS CI
on:
  push:
    branches:
      - master
  repository_dispatch:
  pull_request: {}

env:
  BT_NAME: BibleTime
  BT_VERSION: 3.0.2
  BT_BRANCH: stable-3.0
  QT_VERSION: 5.15.2

jobs:
  mac:
    name: build-mac
    runs-on: [ macOS-10.15 ]

    steps:

    - name: Install dependencies
      run: |
        set -e
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install ccache clucene sword create-dmg
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        host: 'mac'
        target: 'desktop'

    - name: Checkout BibleTime
      run: |
        git clone https://github.com/bibletime/bibletime.git
        cd bibletime
        git checkout ${{ env.BT_BRANCH }}
        ls -l
        
    - name: Checkout BibleTime Docs
      run: |
        git clone https://github.com/bibletime/generated_docs.git

    - name: Configure BibleTime
      shell: bash
      run: |
        mkdir install
        mkdir build
        cd build
        cmake ../bibletime \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX:PATH=../install \
          -DBUILD_HANDBOOK_HTML:BOOL=OFF \
          -DBUILD_HANDBOOK_PDF:BOOL=OFF \
          -DBUILD_HOWTO_HTML:BOOL=OFF \
          -DBUILD_HOWTO_PDF:BOOL=OFF

    - name: Build BibleTime
      shell: bash
      run: |
        cd build
        cmake --build . --config Release

    - name: Install BibleTime
      shell: bash
      run: |
        cd build
        cmake --install . 
        mkdir -p ../install/BibleTime.app/Contents/share/doc/bibletime
        cp -R ../generated_docs/docs/v${{env.BT_VERSION}}/howto ../install/BibleTime.app/Contents/share/doc/bibletime
        cp -R ../generated_docs/docs/v${{env.BT_VERSION}}/handbook ../install/BibleTime.app/Contents/share/doc/bibletime

    - name: make dmg
      shell: bash
      run: |
        cd install
        ln -s /Applications .
        create-dmg ${{env.BT_NAME}}-${{env.BT_VERSION}}.dmg .

    - name: Save BibleTime Installer
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.BT_NAME}}-${{env.BT_VERSION}}.dmg
        path: install/${{env.BT_NAME}}-${{env.BT_VERSION}}.dmg
        retention-days: 5

